/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: living
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConclaveModes {
    #[serde(rename = "PVPMODE_ALL")]
    pub PVPMODE_ALL: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "PVPMODE_TEAMDEATHMATCH")]
    pub PVPMODE_TEAMDEATHMATCH: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "PVPMODE_NONE")]
    pub PVPMODE_NONE: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "PVPMODE_CAPTURETHEFLAG")]
    pub PVPMODE_CAPTURETHEFLAG: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "PVPMODE_SPEEDBALL")]
    pub PVPMODE_SPEEDBALL: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "PVPMODE_DEATHMATCH")]
    pub PVPMODE_DEATHMATCH: Box<crate::models::ConclaveModesPvpmodeAll>,
}

impl ConclaveModes {
    pub fn new(PVPMODE_ALL: crate::models::ConclaveModesPvpmodeAll, PVPMODE_TEAMDEATHMATCH: crate::models::ConclaveModesPvpmodeAll, PVPMODE_NONE: crate::models::ConclaveModesPvpmodeAll, PVPMODE_CAPTURETHEFLAG: crate::models::ConclaveModesPvpmodeAll, PVPMODE_SPEEDBALL: crate::models::ConclaveModesPvpmodeAll, PVPMODE_DEATHMATCH: crate::models::ConclaveModesPvpmodeAll) -> ConclaveModes {
        ConclaveModes {
            PVPMODE_ALL: Box::new(PVPMODE_ALL),
            PVPMODE_TEAMDEATHMATCH: Box::new(PVPMODE_TEAMDEATHMATCH),
            PVPMODE_NONE: Box::new(PVPMODE_NONE),
            PVPMODE_CAPTURETHEFLAG: Box::new(PVPMODE_CAPTURETHEFLAG),
            PVPMODE_SPEEDBALL: Box::new(PVPMODE_SPEEDBALL),
            PVPMODE_DEATHMATCH: Box::new(PVPMODE_DEATHMATCH),
        }
    }
}


