/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: living
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EarthCycle {
    #[serde(rename = "id")]
    pub id: f32,
    #[serde(rename = "expiry")]
    pub expiry: String,
    #[serde(rename = "isDay")]
    pub is_day: bool,
    #[serde(rename = "timeLeft")]
    pub time_left: String,
}

impl EarthCycle {
    pub fn new(id: f32, expiry: String, is_day: bool, time_left: String) -> EarthCycle {
        EarthCycle {
            id,
            expiry,
            is_day,
            time_left,
        }
    }
}


