/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: living
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EventProgressSteps {
    /// Steps in the progress to completion
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    /// Percent progress to completion
    #[serde(rename = "progressAmt", skip_serializing_if = "Option::is_none")]
    pub progress_amt: Option<f32>,
}

impl EventProgressSteps {
    pub fn new() -> EventProgressSteps {
        EventProgressSteps {
            _type: None,
            progress_amt: None,
        }
    }
}


