/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: living
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Factions {
    #[serde(rename = "FC_GRINEER")]
    pub FC_GRINEER: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "FC_CORPUS")]
    pub FC_CORPUS: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "FC_INFESTATION")]
    pub FC_INFESTATION: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "FC_CORRUPTED")]
    pub FC_CORRUPTED: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "FC_OROKIN")]
    pub FC_OROKIN: Box<crate::models::ConclaveModesPvpmodeAll>,
}

impl Factions {
    pub fn new(FC_GRINEER: crate::models::ConclaveModesPvpmodeAll, FC_CORPUS: crate::models::ConclaveModesPvpmodeAll, FC_INFESTATION: crate::models::ConclaveModesPvpmodeAll, FC_CORRUPTED: crate::models::ConclaveModesPvpmodeAll, FC_OROKIN: crate::models::ConclaveModesPvpmodeAll) -> Factions {
        Factions {
            FC_GRINEER: Box::new(FC_GRINEER),
            FC_CORPUS: Box::new(FC_CORPUS),
            FC_INFESTATION: Box::new(FC_INFESTATION),
            FC_CORRUPTED: Box::new(FC_CORRUPTED),
            FC_OROKIN: Box::new(FC_OROKIN),
        }
    }
}


