/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: living
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

/// Faction : A Faction in Warframe

/// A Faction in Warframe
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Faction {
    #[serde(rename = "Orokin")]
    Orokin,
    #[serde(rename = "Corrupted")]
    Corrupted,
    #[serde(rename = "Infested")]
    Infested,
    #[serde(rename = "Corpus")]
    Corpus,
    #[serde(rename = "Grineer")]
    Grineer,
    #[serde(rename = "Tenno")]
    Tenno,

}

impl ToString for Faction {
    fn to_string(&self) -> String {
        match self {
            Self::Orokin => String::from("Orokin"),
            Self::Corrupted => String::from("Corrupted"),
            Self::Infested => String::from("Infested"),
            Self::Corpus => String::from("Corpus"),
            Self::Grineer => String::from("Grineer"),
            Self::Tenno => String::from("Tenno"),
        }
    }
}

impl Default for Faction {
    fn default() -> Faction {
        Self::Orokin
    }
}




