/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: living
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FissureModifiersVoidT1 {
    #[serde(rename = "num")]
    pub num: f32,
    #[serde(rename = "value")]
    pub value: String,
}

impl FissureModifiersVoidT1 {
    pub fn new(num: f32, value: String) -> FissureModifiersVoidT1 {
        FissureModifiersVoidT1 {
            num,
            value,
        }
    }
}


