/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: living
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */

/// InlineResponse200Previous : Estimation data for the last mission that was active. Could also be the current.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse200Previous {
    /// When the mission became or becomes active
    #[serde(rename = "activation", skip_serializing_if = "Option::is_none")]
    pub activation: Option<String>,
    /// When the mission became or becomes inactive
    #[serde(rename = "expiry", skip_serializing_if = "Option::is_none")]
    pub expiry: Option<String>,
}

impl InlineResponse200Previous {
    /// Estimation data for the last mission that was active. Could also be the current.
    pub fn new() -> InlineResponse200Previous {
        InlineResponse200Previous {
            activation: None,
            expiry: None,
        }
    }
}


