/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: living
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvasionFaction {
    #[serde(rename = "reward", skip_serializing_if = "Option::is_none")]
    pub reward: Option<Box<crate::models::Reward>>,
    #[serde(rename = "faction", skip_serializing_if = "Option::is_none")]
    pub faction: Option<crate::models::Faction>,
    #[serde(rename = "factionKey", skip_serializing_if = "Option::is_none")]
    pub faction_key: Option<crate::models::Faction>,
}

impl InvasionFaction {
    pub fn new() -> InvasionFaction {
        InvasionFaction {
            reward: None,
            faction: None,
            faction_key: None,
        }
    }
}


