/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: living
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MissionTypes {
    #[serde(rename = "MT_EXCAVATE")]
    pub MT_EXCAVATE: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_SABOTAGE")]
    pub MT_SABOTAGE: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_MOBILE_DEFENSE")]
    pub MT_MOBILE_DEFENSE: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_ASSASSINATION")]
    pub MT_ASSASSINATION: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_EXTERMINATION")]
    pub MT_EXTERMINATION: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_HIVE")]
    pub MT_HIVE: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_DEFENSE")]
    pub MT_DEFENSE: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_TERRITORY")]
    pub MT_TERRITORY: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_ARENA")]
    pub MT_ARENA: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_PVP")]
    pub MT_PVP: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_RESCUE")]
    pub MT_RESCUE: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_INTEL")]
    pub MT_INTEL: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_SURVIVAL")]
    pub MT_SURVIVAL: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_CAPTURE")]
    pub MT_CAPTURE: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_SECTOR")]
    pub MT_SECTOR: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_RETRIEVAL")]
    pub MT_RETRIEVAL: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_ASSAULT")]
    pub MT_ASSAULT: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "MT_EVACUATION")]
    pub MT_EVACUATION: Box<crate::models::ConclaveModesPvpmodeAll>,
}

impl MissionTypes {
    pub fn new(MT_EXCAVATE: crate::models::ConclaveModesPvpmodeAll, MT_SABOTAGE: crate::models::ConclaveModesPvpmodeAll, MT_MOBILE_DEFENSE: crate::models::ConclaveModesPvpmodeAll, MT_ASSASSINATION: crate::models::ConclaveModesPvpmodeAll, MT_EXTERMINATION: crate::models::ConclaveModesPvpmodeAll, MT_HIVE: crate::models::ConclaveModesPvpmodeAll, MT_DEFENSE: crate::models::ConclaveModesPvpmodeAll, MT_TERRITORY: crate::models::ConclaveModesPvpmodeAll, MT_ARENA: crate::models::ConclaveModesPvpmodeAll, MT_PVP: crate::models::ConclaveModesPvpmodeAll, MT_RESCUE: crate::models::ConclaveModesPvpmodeAll, MT_INTEL: crate::models::ConclaveModesPvpmodeAll, MT_SURVIVAL: crate::models::ConclaveModesPvpmodeAll, MT_CAPTURE: crate::models::ConclaveModesPvpmodeAll, MT_SECTOR: crate::models::ConclaveModesPvpmodeAll, MT_RETRIEVAL: crate::models::ConclaveModesPvpmodeAll, MT_ASSAULT: crate::models::ConclaveModesPvpmodeAll, MT_EVACUATION: crate::models::ConclaveModesPvpmodeAll) -> MissionTypes {
        MissionTypes {
            MT_EXCAVATE: Box::new(MT_EXCAVATE),
            MT_SABOTAGE: Box::new(MT_SABOTAGE),
            MT_MOBILE_DEFENSE: Box::new(MT_MOBILE_DEFENSE),
            MT_ASSASSINATION: Box::new(MT_ASSASSINATION),
            MT_EXTERMINATION: Box::new(MT_EXTERMINATION),
            MT_HIVE: Box::new(MT_HIVE),
            MT_DEFENSE: Box::new(MT_DEFENSE),
            MT_TERRITORY: Box::new(MT_TERRITORY),
            MT_ARENA: Box::new(MT_ARENA),
            MT_PVP: Box::new(MT_PVP),
            MT_RESCUE: Box::new(MT_RESCUE),
            MT_INTEL: Box::new(MT_INTEL),
            MT_SURVIVAL: Box::new(MT_SURVIVAL),
            MT_CAPTURE: Box::new(MT_CAPTURE),
            MT_SECTOR: Box::new(MT_SECTOR),
            MT_RETRIEVAL: Box::new(MT_RETRIEVAL),
            MT_ASSAULT: Box::new(MT_ASSAULT),
            MT_EVACUATION: Box::new(MT_EVACUATION),
        }
    }
}


