/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: living
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ModAllOfLevelStats {
    #[serde(rename = "stats", skip_serializing_if = "Option::is_none")]
    pub stats: Option<Vec<String>>,
}

impl ModAllOfLevelStats {
    pub fn new() -> ModAllOfLevelStats {
        ModAllOfLevelStats {
            stats: None,
        }
    }
}


