/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: living
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RewardCountedItems {
    #[serde(rename = "count")]
    pub count: f32,
    #[serde(rename = "type")]
    pub _type: String,
}

impl RewardCountedItems {
    pub fn new(count: f32, _type: String) -> RewardCountedItems {
        RewardCountedItems {
            count,
            _type,
        }
    }
}


