/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: living
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Riven {
    /// The name of the weapon that this riven is compatible with
    #[serde(rename = "rivenCompatability", skip_serializing_if = "Option::is_none")]
    pub riven_compatability: Option<::std::collections::HashMap<String, crate::models::RivenRivenCompatability>>,
}

impl Riven {
    pub fn new() -> Riven {
        Riven {
            riven_compatability: None,
        }
    }
}


