/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: living
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Simaris {
    #[serde(rename = "target")]
    pub target: String,
    #[serde(rename = "isTargetActive")]
    pub is_target_active: bool,
    #[serde(rename = "asString")]
    pub as_string: String,
}

impl Simaris {
    pub fn new(target: String, is_target_active: bool, as_string: String) -> Simaris {
        Simaris {
            target,
            is_target_active,
            as_string,
        }
    }
}


