/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: living
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SolNode {
    #[serde(rename = "SolKey", skip_serializing_if = "Option::is_none")]
    pub sol_key: Option<Box<crate::models::SolNodeSolKey>>,
}

impl SolNode {
    pub fn new() -> SolNode {
        SolNode {
            sol_key: None,
        }
    }
}


