/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: living
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SortieDataRegions {
    #[serde(rename = "missions", skip_serializing_if = "Option::is_none")]
    pub missions: Option<Vec<serde_json::Value>>,
    #[serde(rename = "name")]
    pub name: String,
}

impl SortieDataRegions {
    pub fn new(name: String) -> SortieDataRegions {
        SortieDataRegions {
            missions: None,
            name,
        }
    }
}


