/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: living
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SortieDataModifierTypes {
    #[serde(rename = "SORTIE_MODIFIER_IMPACT")]
    pub SORTIE_MODIFIER_IMPACT: String,
    #[serde(rename = "SORTIE_MODIFIER_HAZARD_COLD")]
    pub SORTIE_MODIFIER_HAZARD_COLD: String,
    #[serde(rename = "SORTIE_MODIFIER_SECONDARY_ONLY")]
    pub SORTIE_MODIFIER_SECONDARY_ONLY: String,
    #[serde(rename = "SORTIE_MODIFIER_TOXIN")]
    pub SORTIE_MODIFIER_TOXIN: String,
    #[serde(rename = "SORTIE_MODIFIER_ELECTRICITY")]
    pub SORTIE_MODIFIER_ELECTRICITY: String,
    #[serde(rename = "SORTIE_MODIFIER_HAZARD_FOG")]
    pub SORTIE_MODIFIER_HAZARD_FOG: String,
    #[serde(rename = "SORTIE_MODIFIER_HAZARD_MAGNETIC")]
    pub SORTIE_MODIFIER_HAZARD_MAGNETIC: String,
    #[serde(rename = "SORTIE_MODIFIER_ARMOR")]
    pub SORTIE_MODIFIER_ARMOR: String,
    #[serde(rename = "SORTIE_MODIFIER_CORROSIVE")]
    pub SORTIE_MODIFIER_CORROSIVE: String,
    #[serde(rename = "SORTIE_MODIFIER_VIRAL")]
    pub SORTIE_MODIFIER_VIRAL: String,
    #[serde(rename = "SORTIE_MODIFIER_HAZARD_RADIATION")]
    pub SORTIE_MODIFIER_HAZARD_RADIATION: String,
    #[serde(rename = "SORTIE_MODIFIER_SLASH")]
    pub SORTIE_MODIFIER_SLASH: String,
    #[serde(rename = "SORTIE_MODIFIER_POISON")]
    pub SORTIE_MODIFIER_POISON: String,
    #[serde(rename = "SORTIE_MODIFIER_GAS")]
    pub SORTIE_MODIFIER_GAS: String,
    #[serde(rename = "SORTIE_MODIFIER_MAGNETIC")]
    pub SORTIE_MODIFIER_MAGNETIC: String,
    #[serde(rename = "SORTIE_MODIFIER_FIRE")]
    pub SORTIE_MODIFIER_FIRE: String,
    #[serde(rename = "SORTIE_MODIFIER_SNIPER_ONLY")]
    pub SORTIE_MODIFIER_SNIPER_ONLY: String,
    #[serde(rename = "SORTIE_MODIFIER_PUNCTURE")]
    pub SORTIE_MODIFIER_PUNCTURE: String,
    #[serde(rename = "SORTIE_MODIFIER_EXPLOSION")]
    pub SORTIE_MODIFIER_EXPLOSION: String,
    #[serde(rename = "SORTIE_MODIFIER_BOW_ONLY")]
    pub SORTIE_MODIFIER_BOW_ONLY: String,
    #[serde(rename = "SORTIE_MODIFIER_RADIATION")]
    pub SORTIE_MODIFIER_RADIATION: String,
    #[serde(rename = "SORTIE_MODIFIER_SHIELDS")]
    pub SORTIE_MODIFIER_SHIELDS: String,
    #[serde(rename = "SORTIE_MODIFIER_FREEZE")]
    pub SORTIE_MODIFIER_FREEZE: String,
    #[serde(rename = "SORTIE_MODIFIER_HAZARD_FIRE")]
    pub SORTIE_MODIFIER_HAZARD_FIRE: String,
    #[serde(rename = "SORTIE_MODIFIER_EXIMUS")]
    pub SORTIE_MODIFIER_EXIMUS: String,
    #[serde(rename = "SORTIE_MODIFIER_SHOTGUN_ONLY")]
    pub SORTIE_MODIFIER_SHOTGUN_ONLY: String,
    #[serde(rename = "SORTIE_MODIFIER_MELEE_ONLY")]
    pub SORTIE_MODIFIER_MELEE_ONLY: String,
    #[serde(rename = "SORTIE_MODIFIER_RIFLE_ONLY")]
    pub SORTIE_MODIFIER_RIFLE_ONLY: String,
    #[serde(rename = "SORTIE_MODIFIER_HAZARD_ICE")]
    pub SORTIE_MODIFIER_HAZARD_ICE: String,
    #[serde(rename = "SORTIE_MODIFIER_LOW_ENERGY")]
    pub SORTIE_MODIFIER_LOW_ENERGY: String,
}

impl SortieDataModifierTypes {
    pub fn new(SORTIE_MODIFIER_IMPACT: String, SORTIE_MODIFIER_HAZARD_COLD: String, SORTIE_MODIFIER_SECONDARY_ONLY: String, SORTIE_MODIFIER_TOXIN: String, SORTIE_MODIFIER_ELECTRICITY: String, SORTIE_MODIFIER_HAZARD_FOG: String, SORTIE_MODIFIER_HAZARD_MAGNETIC: String, SORTIE_MODIFIER_ARMOR: String, SORTIE_MODIFIER_CORROSIVE: String, SORTIE_MODIFIER_VIRAL: String, SORTIE_MODIFIER_HAZARD_RADIATION: String, SORTIE_MODIFIER_SLASH: String, SORTIE_MODIFIER_POISON: String, SORTIE_MODIFIER_GAS: String, SORTIE_MODIFIER_MAGNETIC: String, SORTIE_MODIFIER_FIRE: String, SORTIE_MODIFIER_SNIPER_ONLY: String, SORTIE_MODIFIER_PUNCTURE: String, SORTIE_MODIFIER_EXPLOSION: String, SORTIE_MODIFIER_BOW_ONLY: String, SORTIE_MODIFIER_RADIATION: String, SORTIE_MODIFIER_SHIELDS: String, SORTIE_MODIFIER_FREEZE: String, SORTIE_MODIFIER_HAZARD_FIRE: String, SORTIE_MODIFIER_EXIMUS: String, SORTIE_MODIFIER_SHOTGUN_ONLY: String, SORTIE_MODIFIER_MELEE_ONLY: String, SORTIE_MODIFIER_RIFLE_ONLY: String, SORTIE_MODIFIER_HAZARD_ICE: String, SORTIE_MODIFIER_LOW_ENERGY: String) -> SortieDataModifierTypes {
        SortieDataModifierTypes {
            SORTIE_MODIFIER_IMPACT,
            SORTIE_MODIFIER_HAZARD_COLD,
            SORTIE_MODIFIER_SECONDARY_ONLY,
            SORTIE_MODIFIER_TOXIN,
            SORTIE_MODIFIER_ELECTRICITY,
            SORTIE_MODIFIER_HAZARD_FOG,
            SORTIE_MODIFIER_HAZARD_MAGNETIC,
            SORTIE_MODIFIER_ARMOR,
            SORTIE_MODIFIER_CORROSIVE,
            SORTIE_MODIFIER_VIRAL,
            SORTIE_MODIFIER_HAZARD_RADIATION,
            SORTIE_MODIFIER_SLASH,
            SORTIE_MODIFIER_POISON,
            SORTIE_MODIFIER_GAS,
            SORTIE_MODIFIER_MAGNETIC,
            SORTIE_MODIFIER_FIRE,
            SORTIE_MODIFIER_SNIPER_ONLY,
            SORTIE_MODIFIER_PUNCTURE,
            SORTIE_MODIFIER_EXPLOSION,
            SORTIE_MODIFIER_BOW_ONLY,
            SORTIE_MODIFIER_RADIATION,
            SORTIE_MODIFIER_SHIELDS,
            SORTIE_MODIFIER_FREEZE,
            SORTIE_MODIFIER_HAZARD_FIRE,
            SORTIE_MODIFIER_EXIMUS,
            SORTIE_MODIFIER_SHOTGUN_ONLY,
            SORTIE_MODIFIER_MELEE_ONLY,
            SORTIE_MODIFIER_RIFLE_ONLY,
            SORTIE_MODIFIER_HAZARD_ICE,
            SORTIE_MODIFIER_LOW_ENERGY,
        }
    }
}


