/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: living
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SortieData {
    #[serde(rename = "modifierTypes")]
    pub modifier_types: Box<crate::models::SortieDataModifierTypes>,
    #[serde(rename = "modifierDescriptions")]
    pub modifier_descriptions: Box<crate::models::SortieDataModifierTypes>,
    #[serde(rename = "bosses")]
    pub bosses: Box<crate::models::SortieDataBosses>,
    #[serde(rename = "endStates")]
    pub end_states: Vec<crate::models::SortieDataEndStates>,
    #[serde(rename = "modifiers")]
    pub modifiers: Vec<serde_json::Value>,
}

impl SortieData {
    pub fn new(modifier_types: crate::models::SortieDataModifierTypes, modifier_descriptions: crate::models::SortieDataModifierTypes, bosses: crate::models::SortieDataBosses, end_states: Vec<crate::models::SortieDataEndStates>, modifiers: Vec<serde_json::Value>) -> SortieData {
        SortieData {
            modifier_types: Box::new(modifier_types),
            modifier_descriptions: Box::new(modifier_descriptions),
            bosses: Box::new(bosses),
            end_states,
            modifiers,
        }
    }
}


