/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: living
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SortieDataBossesSortieBossKela {
    #[serde(rename = "faction")]
    pub faction: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl SortieDataBossesSortieBossKela {
    pub fn new(faction: String, name: String) -> SortieDataBossesSortieBossKela {
        SortieDataBossesSortieBossKela {
            faction,
            name,
        }
    }
}


