/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: living
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SortieAllOf {
    #[serde(rename = "rewardPool")]
    pub reward_pool: String,
    #[serde(rename = "variants")]
    pub variants: Vec<crate::models::SortieAllOfVariants>,
    #[serde(rename = "boss")]
    pub boss: String,
    #[serde(rename = "faction")]
    pub faction: String,
    #[serde(rename = "expired")]
    pub expired: bool,
    #[serde(rename = "eta")]
    pub eta: String,
}

impl SortieAllOf {
    pub fn new(reward_pool: String, variants: Vec<crate::models::SortieAllOfVariants>, boss: String, faction: String, expired: bool, eta: String) -> SortieAllOf {
        SortieAllOf {
            reward_pool,
            variants,
            boss,
            faction,
            expired,
            eta,
        }
    }
}


