/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: living
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpgradeTypes {
    #[serde(rename = "GAMEPLAY_KILL_XP_AMOUNT")]
    pub GAMEPLAY_KILL_XP_AMOUNT: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "GAMEPLAY_PICKUP_AMOUNT")]
    pub GAMEPLAY_PICKUP_AMOUNT: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "GAMEPLAY_MONEY_REWARD_AMOUNT")]
    pub GAMEPLAY_MONEY_REWARD_AMOUNT: Box<crate::models::ConclaveModesPvpmodeAll>,
    #[serde(rename = "GAMEPLAY_MONEY_PICKUP_AMOUNT")]
    pub GAMEPLAY_MONEY_PICKUP_AMOUNT: Box<crate::models::ConclaveModesPvpmodeAll>,
}

impl UpgradeTypes {
    pub fn new(GAMEPLAY_KILL_XP_AMOUNT: crate::models::ConclaveModesPvpmodeAll, GAMEPLAY_PICKUP_AMOUNT: crate::models::ConclaveModesPvpmodeAll, GAMEPLAY_MONEY_REWARD_AMOUNT: crate::models::ConclaveModesPvpmodeAll, GAMEPLAY_MONEY_PICKUP_AMOUNT: crate::models::ConclaveModesPvpmodeAll) -> UpgradeTypes {
        UpgradeTypes {
            GAMEPLAY_KILL_XP_AMOUNT: Box::new(GAMEPLAY_KILL_XP_AMOUNT),
            GAMEPLAY_PICKUP_AMOUNT: Box::new(GAMEPLAY_PICKUP_AMOUNT),
            GAMEPLAY_MONEY_REWARD_AMOUNT: Box::new(GAMEPLAY_MONEY_REWARD_AMOUNT),
            GAMEPLAY_MONEY_PICKUP_AMOUNT: Box::new(GAMEPLAY_MONEY_PICKUP_AMOUNT),
        }
    }
}


