/*
 * WarframeStat.us API
 *
 * Simple API for data from the game Warframe. [Parser Docs](https://wfcd.github.io/warframe-worldstate-parser/) [Items Types](https://github.com/WFCD/warframe-items/blob/master/index.d.ts) 
 *
 * The version of the OpenAPI document: living
 * Contact: tobiah@protonmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoidTraderAllOfInventory {
    /// Item that is being sold
    #[serde(rename = "item", skip_serializing_if = "Option::is_none")]
    pub item: Option<String>,
    /// Amount of ducats required to purchase item
    #[serde(rename = "ducats", skip_serializing_if = "Option::is_none")]
    pub ducats: Option<f32>,
    /// Amount of credits required to purchase item
    #[serde(rename = "credits", skip_serializing_if = "Option::is_none")]
    pub credits: Option<f32>,
}

impl VoidTraderAllOfInventory {
    pub fn new() -> VoidTraderAllOfInventory {
        VoidTraderAllOfInventory {
            item: None,
            ducats: None,
            credits: None,
        }
    }
}


